ProjectShow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
]

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
import home.views

urlpatterns = [
    url(r"^login/$", auth_views.login, {"template_name": "account/login.html"}, name="user_login"),

    url(r'^logout/$', auth_views.logout, {"next_page": 'index_home'
        , "template_name": "account/logout.html"},
        name='user_logout'),

    url(r'^register/$', views.register, name="user_register"),

    url(r'^password-change/$', views.password_change,
        {"post_change_redirect": "/account/password-change-done"}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

    url(r'^password-reset/$', auth_views.password_reset,
        {"template_name": "account/password_reset_form.html",
         "email_template_name": "account/password_reset_email.html",
         "subject_template_name": "account/password_reset_subject.txt",
         "html_email_template_name": "account/password_reset_email.html",
         "post_reset_redirect": "/account/password-reset-done"}, name="password_reset"),

    url(r'^password-reset-done/$', auth_views.password_reset_done,
        {"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.password_reset_confirm, {"template_name": "account/password_reset_confirm.html",
                                            "post_reset_redirect": "/account/password-reset-complete"},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),

    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

article/urls.py
from django.urls import path
from django.conf.urls import url

from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail,
        name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail,
        name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles,
        name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

blog/urls.py
from django.urls import path
import blog.views as view


urlpatterns = [
    path('', view.index, name='blog_home'),
]

article/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name="tag", on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    image_url = models.CharField(max_length=200, default="image_2.jpg")
    column = models.ForeignKey(ArticleColumn, related_name="article_column",
                               on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    # abstract = models.CharField(max_length=300, default=markdown.markdown(body[:70]))

    class Meta:
        # ordering = ("title",)
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        # return "/article/read-article/{0}/{1}".format(self.id, self.slug)
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments", on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms

from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm
from .models import ArticleColumn, ArticlePost, ArticleTag


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html",
                      {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
           # try:
            new_article = article_post_form.save(commit=False)
            new_article.author = request.user
            new_article.column = request.user.article_column.get(id=request.POST['column_id'])
            new_article.save()
            tags = request.POST['tags']
            if tags:
                for atag in json.loads(tags):
                    tag = request.user.tag.get(tag=atag)
                    new_article.article_tag.add(tag)

            return HttpResponse("1")
           # except:
           #     return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns,
                       "article_tags": article_tags})


@login_required(login_url='/account/login')
def article_list(request):
    # articles = ArticlePost.objects.filter(author=request.user)
    # return render(request, "article/column/article_list.html", {"articles":articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html",
                  {"articles": articles, "page": current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",
                      {"article": article, "article_columns": article_columns,
                       "this_article_column": this_article_column,
                       "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html",
                      {"article_tags": article_tags, "article_tag_form": article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("the data cannot be save.")
        else:
            return HttpResponse("sorry, the form is not valid.")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/list/article_detail.html
{% extends "article/base.html" %}

{% load article_tags %}
{% load staticfiles %}

{% block title %}<title> {{ article.title }}</title>{% endblock %}

{% block content %}

{% with total_likes=article.users_like.count users_like=article.users_like.all %}

<div class="container">
    <div class="col-md-9">
        <header>
            <h1>{{ article.title }}</h1>
            <p>
                <a href="{% url 'article:author_articles' article.author.username %}">
                    {{ article.author.username }}
                </a>
                <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up"><span id="likeCount">{{ total_likes }}</span>like{{ total_likes | pluralize }}</span>
                <span style="margin-left: 20px">{{ total_views }} view{{ total_views | pluralize }}</span>
                <span style="margin-left: 20px"> {{article.body| count_word}} words</span>
                <span style="margin-left: 20px">Last Updated: {{ article.updated }}</span>
            </p>
            <p><span style="margin-right: 10px"><strong>Tags:</strong></span> {{ article.article_tag.all | join:", "}}</p>
        </header>

        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
        <div id='editormd-view'>

        <textarea id="append-test" style="display:none;">
{{ article.body }}
	    </textarea>
            <!--textarea id="append-test" style="display:none;">
    {{ article.body }}
            </textarea-->
            <!--{{ article.body | markdown }}-->
        </div>
        <div>
            <p class="text-center">
                <a onclick="like_article({{article.id}}, 'like')" href="#"><span
                        class="glyphicon glyphicon-thumbs-up">like</span></a>
                <a onclick="like_article({{article.id}}, 'unlike')" href="#"><span
                        style="margin-left: 15px;"
                        class="glyphicon glyphicon-thumbs-down">dislike</span></a>
            </p>
        </div>
        <div>
            <p class="text-center"><strong>点赞本文的读者</strong></p>
            {% for user in article.users_like.all %}
            <p class="text-center">{{ user.username }}</p>
            {% empty %}
            <p class="text-center">还没有人对此文章表态</p>
            {% endfor %}
        </div>
        <hr>
        <div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有{{ comments.count }}评论</h3>
            {% for comment in article.comments.all %}
            <div>
                <p><strong>{{ comment.commentator }}</strong>说：</p>
                <p style="margin-left:40px;">{{ comment.body }}</p>
            </div>
            {% empty %}
            <p>没有评论</p>
            {% endfor %}

            <h3><span class="glyphicon glyphicon-send"></span>看文章，发评论，不要沉默</h3>
            <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">昵称</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
                    </div>
                </div>
            </form>
        </div>

    </div>
    <div class="col-md-3">
        <p class="text-center">
        <h3>最受欢迎文章</h3></p>
        <ol>
            {% for article_rank in most_viewed %}
            <li>
                <a href="{{article_rank.get_url_path}}">{{ article_rank.title }}</a>
            </li>
            {% endfor %}
        </ol>
        <hr>
        <p class="text-center">
        <h3>最新文章</h3></p>
        <div>{% latest_articles 4 %}</div>

        <hr>
        <p class="text-center">
        <h3>最多评论文章</h3></p>
        {% most_commented_articles as most_comments %}
        <div>
            <ul>
                {% for comment_article in most_comments %}
                <li>
                    <a href="{{comment_article.get_url_path}}">{{ comment_article.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>

        <hr>
        <p class="text-center">
        <h3>推荐相似文章</h3></p>
        <div>
            {% for similar in similar_articles %}
            <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a></p>
            {% empty %}
            <p>Sorry, 没有相似文章</p>
            {% endfor %}
        </div>
    </div>

</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    $(function () {
        editormd.markdownToHTML("editormd-view", {
            htmlDecode: "style,script,iframe",  // you can filter tags decode
            emoji: true,
            taskList: true,
            tex: true,  // 默认不解析
            flowChart: true,  // 默认不解析
            sequenceDiagram: true,  // 默认不解析
        });
    });

    function like_article(id, action) {
        $.ajax({
            url: "{% url 'article:like_article' %}",
            type: "POST",
            data: {"id": id, "action": action},
            success: function (e) {
                var x=document.getElementById("likeCount").innerHTML;
                if (e == "2") {
                    layer.msg("感谢点赞");
                    x=parseInt(x)+1;
                    document.getElementById("likeCount").innerHTML=x;
                } else if(e == "4"){
                    layer.msg("我会继续努力");
                    x=parseInt(x)-1;
                    document.getElementById("likeCount").innerHTML=x;
                }else if(e == "1"){
                    layer.msg("你已经点过赞了哦");
                }else if(e == "3"){
                    layer.msg("你之前没有点赞哦");
                }else {
                    layer.msg("请先登录");
                }
            },

        });
    }
</script>
<link href="{% static 'css/pygments.css' %}" rel="stylesheet">
{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% load static %}
{% load article_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="articles">
    <meta name="author" content="strivexj">
    <link href="{% static 'images/icon.png' %}" rel="SHORTCUT ICON">
    <title>Articles</title>
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:index' %}">strivexj's site</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#">{{ user.username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'account:user_logout' %}">Log
                    Out</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'account:user_register' %}">Register</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'account:user_login' %}">Log
                    In</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="#">About</a></li>

            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url({% static 'images/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h2>Share what you learned with others</h2>
                    <span class="subheading">There are {% total_articles %} articles.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for article in articles %}
            <div class="post-preview">
                <a href="{{article.get_url_path}}">
                    <h2 class="post-title">
                        {{article.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{article.body|slice:'300'|markdownabstract}}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a>
                    on {{article.created}}</p>
            </div>
            <hr>
            {% endfor %}

            <!-- Pager -->
            <div class="clearfix">
                {% include "paginator.html" %}
                <!--<a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>-->
            </div>
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <!-- <li class="list-inline-item">
                       <a href="#">
                         <span class="fa-stack fa-lg">
                           <i class="fa fa-circle fa-stack-2x"></i>
                           <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                         </span>
                       </a>
                     </li>
                     <li class="list-inline-item">
                       <a href="#">
                         <span class="fa-stack fa-lg">
                           <i class="fa fa-circle fa-stack-2x"></i>
                           <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                         </span>
                       </a>
                     </li>-->
                    <li class="list-inline-item">
                        <a href="https://github.com/strivexj">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; strivexj 2018</p>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- Custom scripts for this template -->
<script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>

</html>

templates/article/list/article_titles2.html
{% load static %}
{% load article_tags %}
<section class="ftco-section ftco-counter img" id="section-counter"
         style="background-image: url(../static/images/bg_1.jpg);" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <strong class="number" data-number="{% total_articles %}">0</strong>
                                <span>博客量</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <strong class="number" data-number="2000">0</strong>
                                <span>项目个数</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <strong class="number" data-number="520">0</strong>
                                <span>VIP用户</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <strong class="number" data-number="1314">0</strong>
                                <span>博客量</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="services-section bg-light" >
    <div class="container" style="text-align:center">
        <div class="row d-flex">
            <div class="col-md-3 d-flex align-self-stretch ftco-animate center">
                <div class="media block-6 services d-block">
                    <div class="icon">
                        <a href="{% url 'article:article_post' %}">
                          <span class="flaticon-yatch" href="{% url 'article:article_post' %}"></span>
                        </a>
                    </div>
                    <div class="media-body">
                        <a class="heading mb-3" href="{% url 'article:article_post' %}">发表文章</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            {% for article in articles %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry align-self-stretch">
                    <a href="{{article.get_url_path}}" class="block-20"
                       style="background-image: url('../static/images/image_2.jpg');">
                    </a>
                    <div class="text">
                        <span class="tag">Tips, Travel</span>
                        <h3 class="heading mt-3"><a href="{{article.get_url_path}}">{{article.title}}</a>
                        </h3>
                        <div class="meta mb-3">
                            <div><a href="#">{{article.created}}</a></div>
                            <div><a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></div>
                            <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                        <ul>
                        <li><a href="#">&lt;</a></li>
                        {% for item in total_pages %}
                            {% if item == page.number %}
                            <li class="active"><a href="?page={{ item }}">{{ item }}</a></li>
                            {% else %}
                            <li><a href="?page={{ item }}">{{ item }}</a></li>
                            {% endif %}
                        {% endfor %}
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
    	<a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>