ProjectShow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
]

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
import home.views

urlpatterns = [
    url(r"^login/$", auth_views.login, {"template_name": "account/login.html"}, name="user_login"),

    url(r'^logout/$', auth_views.logout, {"next_page": 'index_home'
        , "template_name": "account/logout.html"},
        name='user_logout'),

    url(r'^register/$', views.register, name="user_register"),

    url(r'^password-change/$', views.password_change,
        {"post_change_redirect": "/account/password-change-done"}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

    url(r'^password-reset/$', auth_views.password_reset,
        {"template_name": "account/password_reset_form.html",
         "email_template_name": "account/password_reset_email.html",
         "subject_template_name": "account/password_reset_subject.txt",
         "html_email_template_name": "account/password_reset_email.html",
         "post_reset_redirect": "/account/password-reset-done"}, name="password_reset"),

    url(r'^password-reset-done/$', auth_views.password_reset_done,
        {"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.password_reset_confirm, {"template_name": "account/password_reset_confirm.html",
                                            "post_reset_redirect": "/account/password-reset-complete"},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),

    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

article/urls.py
from django.urls import path
from django.conf.urls import url

from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail,
        name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail,
        name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles,
        name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

blog/urls.py
from django.urls import path
import blog.views as view


urlpatterns = [
    path('', view.index, name='blog_home'),
]

templates/adaptation_detail.html
{% extends "base.html" %}
{% block title %}
<title>Adaptation</title>
{% endblock %}
{% block content %}

<div class="row text-center vertical-middle-sm">
    <h1>Course</h1>
</div>
<div class="container">
    {{adaptation.html|safe}}
</div>
<div id="bottom">
    <a href="{{adaptation.url}}"> {{adaptation.school}} &nbsp;&nbsp;&nbsp;</a>

    <a href="/valid/{{adaptation.id}}?origin={{adaptation.valid}}">
        Valid:{{adaptation.valid}}&nbsp;&nbsp;&nbsp; </a>
    <a href="/adapted/{{adaptation.id}}?origin={{adaptation.adapted}}">
        Adapted:{{adaptation.adapted}} &nbsp;&nbsp;&nbsp;</a>
</div>
{% endblock %}

templates/adaptation_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2  class="text-center">Apply for Adaptation</h2>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'home:adaptation_form' %}" class="form">
    {% csrf_token %}
    <div class="col-md-4 col-sm-offset-4 ">
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary center-block">Apply for Adaptation</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'home:index' %}" />
    </div>
</form>
{% endblock content %}

templates/adaptation_list.html
{% extends "base.html" %}
{% block title %}
<title>Adaptation</title>
{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h2>课表申请适配列表({{total_valid}}/{{total}})</h2>
</div>
<div class="container">
        <table border="1" cellpadding="10" align="center">
            <tr>
                <td>Read</td>
                <td>School</td>
                <td>Eas</td>
                <td>Type</td>
                <td>Valid</td>
                <td>Adapted</td>
                <td>Delete</td>
                <td>Contact</td>
            </tr>
            {% for adaptation in adaptations %}
            <tr>
                <td>{{adaptation.read}}</td>
                <td> <a href="{{adaptation.url}}"> {{adaptation.school}}</a> </td>
                <td>{{adaptation.eas}}</td>
                <td> <a href="/adaptationdetail/{{adaptation.id}}#bottom"> {{adaptation.type}}</a> </td>
                <td> <a href="/adapted/{{adaptation.id}}?origin={{adaptation.adapted}}">
                    {{adaptation.adapted}}</a> </td>
                <td> <a href="/valid/{{adaptation.id}}?origin={{adaptation.valid}}">
                    {{adaptation.valid}}</a> </td>

                <td> <a href="/delete/{{adaptation.id}}">
                    Delete </a> </td>
                <td>{{adaptation.contact}}</td>
            </tr>
            {% endfor %}
        </table>
</div>
{% endblock %}

templates/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

{#    <link href="{% static 'images/icon.png' %}" rel="SHORTCUT ICON">#}
    {% block title%} {% endblock title %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style type="text/css">
        html, body {
            height: 100%
        }

        .footer {
            height: 55px;
            background-color: #eee;
        }

        .container {
            min-height: 85%
        }

        .content {
            padding-bottom: 30px;
            overflow: hidden;
        }
        td{
            padding: 10px;
        }
    </style>
</head>
{% include "css_include.html" %}
<body>
{%include "header.html"%}
<div style="height: 100px; background: #222831;">

</div>
<div class="container">
    <div class="content">
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>
{%include "footer.html"%}
</body>
</html>

templates/css_include.html
{% load static %}
{% load bootstrap3 %}
<head>
    <title>PhangCheng - A show website</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_javascript %}
    {% bootstrap_css %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">

    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <noscript>
        <link rel="stylesheet" type="text/css" href="{% static "css/noscript.css" %}" />
    </noscript>

  </head>

templates/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">PhangChen</h2>
                    <p>The website to save the memory and the project that you do in the
                        campus. If you have the ability, you can show you project in our
                    website too.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">About Us</a></li>
                        <li><a href="#" class="py-2 d-block">Online enquiry</a></li>
                        <li><a href="#" class="py-2 d-block">Call Us</a></li>
                        <li><a href="#" class="py-2 d-block">General enquiries</a></li>
                        <li><a href="#" class="py-2 d-block">Booking Conditions</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy and Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Refund policy</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Experience</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url "project_home" %}" class="py-2 d-block">Project</a></li>
                        <li><a href="{% url "blog_home" %}" class="py-2 d-block">Blog</a></li>
                        <li><a href="{% url "contact_home" %}" class="py-2 d-block">Contact</a></li>
                        <li><a href="#" class="py-2 d-block">VIP</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="tel://1234567920"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="mailto:info@yoursite.com"><span class="icon icon-envelope"></span><span class="text">1208589984@qq.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    Colorlib All rights reserved <a href="http://www.cssmoban.com/" target="_blank"
                                                                     title="PhangCheng">彭伟航，成文杰</a> - Collect from <a
                        href="http://www.cssmoban.com/" title="网页模板" target="_blank">软件程序作页</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index_home' %}">PhangCheng</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{% url 'index_home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'project_home' %}" class="nav-link">Project</a></li>
                <li class="nav-item"><a href="{% url 'blog_home' %}" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="{% url 'contact_home' %}" class="nav-link">Contact</a></li>
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle'
                                style="background: transparent; color: #b3b3b3;" type='button'
                                id='dropdownMenu' data-toggle='dropdown'>
                            {{ user.username }}</button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}" style="color: #0a001f">Change Password</a></li>
                            <li><a href="{% url 'article:article_column' %}" style="color: #0a001f">Manage</a></li>
                            <li><a href="#" style="color: #0a001f">Help</a></li>
                            <li><a href="{% url 'account:user_logout' %}" style="color: #0a001f">Sign Out</a></li>
                        </ul>
                    </div>
                </li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'account:user_login' %}" class="nav-link">Sign In</a></li>
                    <li class="nav-item"><a href="{% url 'account:user_register' %}" class="nav-link">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/js_include.html
<!-- loader -->
{% load static %}
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "js/jquery.waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.stellar.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/aos.js" %}"></script>
<script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
<script src="{% static "js/bootstrap-datepicker.js" %}"></script>
{#<script src="{% static "js/jquery.timepicker.min.js" %}"></script>#}
<script src="{% static "js/scrollax.min.js" %}"></script>

<script src="{% static "js/google-map.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<script src="{% static "js/post_image.js" %}"></script>
<script src="{% static "js/image_option.js" %}"></script>
<script src="{% static "js/jquery-1.7.2.min.js" %}"></script>
<script src="{% static "js/jquery.circlemouse.js" %}"></script>
<script src="{% static "js/modernizr.custom.72835.js" %}"></script>

templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}    
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>